@startuml
skinparam rectangle<<behavior>> {
	roundCorner 25
}
sprite $bProcess jar:archimate/business-process
sprite $aService jar:archimate/application-service
sprite $aComponent jar:archimate/application-component


rectangle "easy-wt-desktop"  as DESKTOP <<$aComponent>><<behavior>> #Business
rectangle "easy-wt-server" as SERVER <<$aComponent>><<behavior>> #Business
rectangle "easy-wt-web" as WEB <<$aService>><<behavior>> #Application
rectangle "easy-wt-report-web" as REPORT <<$aService>><<behavior>> #Application


rectangle "database-core" as DATABASE <<$aService>><<behavior>> #Application
rectangle "ui-shared" as UI <<$aService>><<behavior>> #Application
rectangle "browser-core" as BROWSER <<$aService>><<behavior>> #Application
rectangle "easy-wt-core" as CORE <<$aService>><<behavior>> #Application


REPORT -up-> DESKTOP

REPORT -up-> SERVER

WEB -left-> SERVER

UI -up-> WEB
UI -up-> REPORT


CORE -up-> DESKTOP
CORE -up-> SERVER

BROWSER -up-> CORE
DATABASE -up-> CORE

legend left
模块解释
====
<$aComponent> easy-wt-server: 服务端,提供http接口
====
<$aComponent> easy-wt-desktop: 桌面客户端
====
<$aService> easy-wt-web:UI界面,作为easy-wt-server的客户端、作为easy-wt-desktop的UI
====
<$aService> easy-wt-report-web:导出html和pdf报告的页面
====
<$aService> browser-core: 浏览器调度的模块
====
<$aService> database-core : 数据库操作的模块
====
<$aService> ui-shared : easy-wt-report-web和easy-wt-web共用的UI组件
====
<$aService> Common : 公用模块,定义了共用的接口、类、类型,被其他所有模块依赖
endlegend
@enduml
